name: Build Godot Project

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: GraveyardShift
  
jobs:
  export_web:
    name: HTML5 Export
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v4.7.0
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.0-stable/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.0-stable/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          use_godot_4: true
          
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/linux
          itchUsername: badcop
          itchGameId: dreams
          buildChannel: linux
